=== nafiuzzamanparves/XmlParser/resource/First.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="isdb">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="round" maxOccurs="4">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="batch" type="xs:integer" />
                            <xs:element name="student" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string" />
                                        <xs:element name="age" type="xs:integer" />
                                        <xs:element name="address">
                                            <xs:complexType mixed="true">
                                                <xs:sequence minOccurs="0">
                                                    <xs:element name="district" minOccurs="0"
                                                        type="xs:string" />
                                                    <xs:element name="thana" minOccurs="0"
                                                        type="xs:string" />
                                                    <xs:element name="village" minOccurs="0"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nafiuzzamanparves/XmlParser/resource/First.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- <?xml-model href="iqram.dtd"?> -->
<!-- <!DOCTYPE isdb SYSTEM "iqram.dtd"> -->
<!-- <?xml-model href="First.xsd"?> -->
<isdb xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="First.xsd">
    <round>
        <batch>62</batch>
        <student>
            <name>Iqramul</name>
            <age>20</age>
            <address>
                <district>Dhaka</district>
                <thana>Araihazari</thana>
                <village>Mahmudpur</village>
            </address>
        </student>
        <student>
            <name>Omar Faruq</name>
            <age>21</age>
            <address>456 Elm St.</address>
        </student>
        <student>
            <name>Bithy</name>
            <age>22</age>
            <address>789 Oak St.</address>
        </student>
        <student>
            <name>Meme</name>
            <age>23</age>
            <address>1011 Pine St.</address>
        </student>
    </round>
    <round>
        <batch>46</batch>
        <student>
            <name>Parves</name>
            <age>20</age>
            <address>
                <district>Rajbari</district>
                <thana>Rajbari</thana>
                <village>Mahmudpur</village>
            </address>
        </student>
    </round>
    <round>
        <batch>85</batch>
        <student>
            <name>Iqramul</name>
            <age>20</age>
            <address>
                <district>Dhaka</district>
                <thana>Araihazari</thana>
                <village>Mahmudpur</village>
            </address>
        </student>
    </round>
</isdb>
